name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install dependencies
      run: dotnet restore mydotnet.sln
    - name: Build
      run: dotnet build mydotnet.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test mydotnet.sln --no-restore --verbosity normal
